TRUNCATE TABLE ratings, comments, chapters, series RESTART IDENTITY CASCADE;

INSERT INTO series (title, synopsis, type) VALUES
  ('Dr. Stone', 'Tras un fenomeno que petrifica a toda la humanidad, Senku Ishigami despierta miles de anios despues y decide reconstruir la civilizacion usando la ciencia.', 'anime'),
  ('Fire Force', 'En un mundo donde las personas pueden combustionar espontaneamente, la Compania 8 lucha contra los Infernales y descubre la verdad detras del fenomeno.', 'anime'),
  ('One Piece', 'Monkey D. Luffy zarpa con su tripulacion de los Sombrero de Paja en busca del legendario tesoro One Piece para convertirse en el Rey de los Piratas.', 'anime'),
  ('Naruto Shippuden', 'Naruto Uzumaki regresa tras dos anios y medio de entrenamiento para enfrentar a Akatsuki y proteger a sus amigos en una guerra ninja a gran escala.', 'anime'),
  ('Oshi no Ko', 'Un medico y su paciente terminal renacen como los hijos gemelos de su idol favorita, descubriendo el lado oscuro de la industria del entretenimiento japonesa.', 'anime'),
  ('Shigatsu wa Kimi no Uso', 'Kosei Arima, un prodigio del piano que perdio la capacidad de oir su propia musica, vuelve a tocar gracias a una violinista llamada Kaori Miyazono.', 'anime'),
  ('Oyasumi Punpun', 'La vida de Punpun Onodera desde su infancia hasta la adultez, explorando el amor, la depresion, la familia y la perdida en un retrato crudo y melancolico.', 'manga'),
  ('Berserk', 'Guts, el Espadachin Negro, busca venganza contra Griffith y los God Hand mientras carga con la marca del sacrificio en un mundo medieval oscuro.', 'manga'),
  ('Vagabond', 'Adaptacion de la novela Musashi de Eiji Yoshikawa que sigue a Shinmen Takezo en su transformacion en el legendario espadachin Miyamoto Musashi.', 'manga'),
  ('Vinland Saga', 'Thorfinn busca venganza contra Askeladd, el mercenario que mato a su padre, en una epopeya vikinga sobre guerra, esclavitud y redencion.', 'manga'),
  ('Chainsaw Man', 'Denji, un joven endeudado con la yakuza, fusiona su cuerpo con su demonio mascota Pochita y se convierte en Chainsaw Man para sobrevivir.', 'manga'),
  ('Monster', 'El doctor Kenzo Tenma salva la vida de un nino llamado Johan, sin saber que se convertira en un asesino en serie que destruira todo a su paso.', 'manga');

INSERT INTO chapters (series_id, number, title) VALUES
  (1, 1, 'Mundo de Piedra'),
  (1, 2, 'El Rey del Mundo de Piedra'),
  (1, 3, 'Armas de la Ciencia'),
  (1, 4, 'Lanza la Senial de Humo'),
  (1, 5, 'Camino de Piedra'),

  (2, 1, 'Shinra Kusakabe se Enlista'),
  (2, 2, 'El Corazon de un Soldado del Fuego'),
  (2, 3, 'Los Juegos de los Soldados Novatos'),
  (2, 4, 'El Heroe y la Princesa'),
  (2, 5, 'Blanco, Negro y Gris'),

  (3, 1, 'Soy Luffy! El Hombre que Sera el Rey de los Piratas!'),
  (3, 2, 'Aparece el Gran Espadachin'),
  (3, 3, 'Morgan vs. Luffy'),
  (3, 4, 'El Pasado de Luffy! Aparece Shanks el Pelirrojo!'),
  (3, 5, 'Miedo, Poder Misterioso! El Capitan Payaso Buggy!'),
  (3, 6, 'Situacion Desesperada! Mohji el Domador vs. Luffy!'),
  (3, 7, 'Gran Duelo! Zoro el Espadachin vs. Cabaji el Acrobata!'),

  (4, 1, 'El Regreso a Casa'),
  (4, 2, 'Akatsuki Hace su Movimiento'),
  (4, 3, 'Los Resultados del Entrenamiento'),
  (4, 4, 'Jinchuriki de la Arena'),
  (4, 5, 'El Kazekage se Mantiene en Pie'),
  (4, 6, 'Mision Cumplida'),

  (5, 1, 'Madre e Hijos'),
  (5, 2, 'Objetivos'),
  (5, 3, 'Reality Show'),
  (5, 4, 'Idol'),
  (5, 5, 'Original'),

  (6, 1, 'Monotono / Colorido'),
  (6, 2, 'Amigo A'),
  (6, 3, 'Dentro de la Primavera'),
  (6, 4, 'El Viaje'),
  (6, 5, 'Adios, Heroe'),

  (7, 1, 'Punpun'),
  (7, 30, 'Aiko'),
  (7, 80, 'Familia'),
  (7, 120, 'Quebrandose'),
  (7, 147, 'Adios'),

  (8, 1, 'El Espadachin Negro'),
  (8, 12, 'La Edad de Oro'),
  (8, 86, 'El Eclipse'),
  (8, 174, 'Conviccion'),
  (8, 250, 'Fantasia'),

  (9, 1, 'El Nacimiento de Musashi'),
  (9, 50, 'Yoshioka'),
  (9, 150, 'Inei'),
  (9, 250, 'Kojiro'),
  (9, 327, 'La Espada'),

  (10, 1, 'En Algun Otro Lugar'),
  (10, 25, 'La Batalla del Puente de Londres'),
  (10, 55, 'Arco del Esclavo'),
  (10, 100, 'La Expedicion del Este'),
  (10, 178, 'Vinland'),

  (11, 1, 'Perro y Motosierra'),
  (11, 38, 'Chica Bomba'),
  (11, 74, 'El Heroe del Infierno'),
  (11, 97, 'Aki y Power'),
  (11, 100, 'El Final'),

  (12, 1, 'Herr Doktor Tenma'),
  (12, 30, 'La Mansion de las Rosas'),
  (12, 80, 'Kinderheim 511'),
  (12, 130, 'El Verdadero Monstruo'),
  (12, 162, 'Al Final de la Historia');

INSERT INTO ratings (series_id, score) VALUES
  (1, 9), (1, 10), (1, 8), (1, 9),
  (2, 8), (2, 7), (2, 9), (2, 8),
  (3, 10), (3, 10), (3, 9), (3, 10), (3, 8),
  (4, 9), (4, 10), (4, 9), (4, 8),
  (5, 9), (5, 10), (5, 8),
  (6, 10), (6, 10), (6, 9), (6, 10),
  (7, 10), (7, 9), (7, 10), (7, 10),
  (8, 10), (8, 10), (8, 10), (8, 9), (8, 10),
  (9, 10), (9, 9), (9, 10), (9, 10),
  (10, 10), (10, 9), (10, 10), (10, 10),
  (11, 9), (11, 8), (11, 10), (11, 9),
  (12, 10), (12, 10), (12, 9), (12, 10);

INSERT INTO comments (series_id, chapter_id, author, content) VALUES
  (1, NULL, 'TaiyoFan', 'La mezcla de ciencia y aventura es brillante, Senku es un genio.'),
  (1, NULL, 'KohakuLover', 'El ritmo de la historia engancha desde el primer episodio.'),
  (2, NULL, 'BurningSoul', 'La animacion del fuego es una locura, Studio David Production se lucio.'),
  (3, NULL, 'StrawHat99', 'Despues de 1000 capitulos sigue siendo el mejor shounen de todos los tiempos.'),
  (3, NULL, 'GrandLineFan', 'Wano arc fue una obra maestra absoluta.'),
  (4, NULL, 'NinjaWay', 'La pelea de Pain sigue siendo uno de los mejores momentos del anime.'),
  (5, NULL, 'AquaStan', 'La cancion de YOASOBI Idol me dio escalofrios la primera vez.'),
  (6, NULL, 'PianoTears', 'Llore como nunca con el final, Kaori para siempre en el corazon.'),
  (7, NULL, 'PunpunForever', 'Asano Inio te destruye emocionalmente, este manga deja huella.'),
  (7, NULL, 'AikoLost', 'Lectura pesada pero imprescindible, no es para cualquiera.'),
  (8, NULL, 'BlackSwordsman', 'Miura fue un genio absoluto, el arte de Berserk no tiene comparacion.'),
  (8, NULL, 'GuyverBob', 'Descansa en paz Miura sensei, tu obra vivira para siempre.'),
  (9, NULL, 'MusashiPath', 'El arte de Inoue es de los mejores que he visto en mi vida.'),
  (10, NULL, 'ThorfinnFan', 'El cambio de Thorfinn de venganza a pacifismo es una obra maestra narrativa.'),
  (11, NULL, 'PochitaCult', 'Fujimoto rompio todas las reglas del shounen y funciono.'),
  (12, NULL, 'JohanLiebert', 'Urasawa construye tension como nadie, cada capitulo es perfecto.'),
  (NULL, 1, 'CienciaPower', 'El opening del primer capitulo te mete en el mundo al instante.'),
  (NULL, 11, 'PirateKing', 'El primer episodio de One Piece es historico, Shanks aun no aparecia tanto.'),
  (NULL, 18, 'SasukeFan', 'El reencuentro del equipo 7 con Naruto despues de los 2 anios fue emocionante.'),
  (NULL, 24, 'GoroDocu', 'El primer capitulo te rompe en mil pedazos sin avisar.'),
  (NULL, 29, 'MelodyHeart', 'La escena del concurso es pura emocion, la musica te transporta.'),
  (NULL, 34, 'YoungPunpun', 'El primer capitulo parece inocente pero ya esta sembrando todo el dolor que viene.'),
  (NULL, 41, 'EclipseScar', 'El Eclipse es de las cosas mas perturbadoras que he leido jamas.'),
  (NULL, 50, 'VinlandHope', 'El cambio de tono cuando Thorfinn llega como esclavo cambia todo el manga.'),
  (NULL, 60, 'TenmaFan', 'El primer capitulo plantea el dilema moral perfecto, queres seguir leyendo de inmediato.');
